Citizen.CreateThread(function()
    --[[ Cars --]]
    AddTextEntry("flatbed3", "flatbed3")
    AddTextEntry("forklift2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("MRTASTY", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("TACO2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("TRASH3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("admiral3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("castella", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("argento", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("elegyrh7", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("deluxogt", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("nspeedo", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("MESAR", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("robin", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("arias", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sptamworth", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sigma3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("scout", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("cypherct", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sunriser", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("kawaii", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("taranis", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("TORRENCE", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("zion4", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("yosemiteswb", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("zodiac", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("cararv", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pony", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("polmav", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sandroamer", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("speedobox", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("rumpo", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("recursion", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("rentalbus", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("muler", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("mulef", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("maverick2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("newsmav", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("idaho", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("galaxyroamer", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("elegyw", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("coyote", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("coachrv", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("boxville7", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("trailers2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("trailers3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("tvtrailer", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sadlerrt", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("rumpobox", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sadler6", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sadler7", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sadler8", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("roadrunnerciv", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("riata3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("riata4", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("guardianrv", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sandkingrv", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    -- [[ Trailers ]]
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    -- [[ Emergency Vehicles ]]
    AddTextEntry("lssdalamo", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("police3slick", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("police3umk", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pigeonp", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("sahp2stx", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("RATCHET", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("ambulance2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apolicecoq", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apolicecoq2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("aemsv450", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("nkbuffalos", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("emsnspeedo", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("emsroamer", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("nkcruiser", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu6", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu7", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu9", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu10", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu13", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu14", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceu15", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("apoliceub", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("stanier2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pbus", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pbus3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pcar", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("psuva", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("ptruck", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("pvan", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("saspacar", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("saspacar2", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("saspacar3", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("saspacar4", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("poldom", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("nkscout", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    -- [[ MOTORCYCLES ]] --
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    --[[ Cycles --]]
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    --[[ Aircraft --]]
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")

    --[[ Boats --]]
    AddTextEntry("SPAWN NAME", "NAME AND DESCRIPTION OF VEHICLE")
end)
